# Generated by Django 5.1.2 on 2024-11-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('MOVIE', 'Movie'), ('MUSIC', 'Music'), ('ANIME', 'Anime')], default='MUSIC', max_length=10),
        ),
    ]
