# Generated by Django 5.1.2 on 2024-11-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('ANIME', 'Anime')], default='MUSIC', max_length=10),
        ),
    ]
