# Generated by Django 5.1.3 on 2024-11-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('ANIME', 'Anime'), ('GAME', 'Game'), ('OTHER', 'Other')], default='MUSIC', max_length=10),
        ),
    ]
